service: surveyless

provider: 
  name: aws
  runtime: python3.6
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  # CreateSurveyFunction:
  #   handler: CreateSurveyFunction/lambda_function.lambda_handler
  #   runtime: python3.6
  #   description: ''
  #   memorySize: 512
  #   timeout: 15
   ## CodeUri: .debug/
    # events:
    #   - http: 
    #       path: /createSurvey
    #       method: POST
    #       cors: true
  create:
    handler: CreateSurvey/create.create
    events:
      - http:
          path: survey
          method: post
          cors: true
  list:
    handler: CreateSurvey/list.list
    events:
      - http:
          path: survey
          method: get
          cors: true

  get:
    handler: CreateSurvey/get.get
    events:
      - http:
          path: survey/{id}
          method: get
          cors: true

  update:
    handler: CreateSurvey/update.update
    events:
      - http:
          path: survey/{id}
          method: put
          cors: true

  delete:
    handler: CreateSurvey/delete.delete
    events:
      - http:
          path: survey/{id}
          method: delete
          cors: true

resources:
  Resources:
    surveyQuestions:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: surveyQuestionsInfo
        AttributeDefinitions:
          - AttributeName: survey_unique_id
            AttributeType: S
        KeySchema:
  # TODO: consider different keyType options?
          - AttributeName: survey_unique_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    surveyResponses:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: surveyResponses
        AttributeDefinitions:
          - AttributeName: survey_unique_id_question_text
            AttributeType: S
        KeySchema:
  # TODO: consider different keyType options?
          - AttributeName: survey_unique_id_question_text
            KeyType: HASH 
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    codeToSurvey:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: codeToSurvey
        AttributeDefinitions:
          - AttributeName: survey_code
            AttributeType: S
        KeySchema:
  # TODO: consider different keyType options?
          - AttributeName: survey_code
            KeyType: HASH 
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    # CreateSurveyFunctionPermission:
    #   Type: 'AWS::Lambda::Permission'
    #   Properties:
    #     Action: 'lambda:InvokeFunction'
    #     FunctionName:
    #       'Fn::GetAtt':
    #         - CreateSurveyFunction
    #         - Arn
    #     Principal: apigateway.amazonaws.com
    #     SourceArn:
    #       'Fn::Sub': 'arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:*/*/*/*'