Resources:
  surveyQuestions:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: surveyQuestionsInfo
      AttributeDefinitions:
        - AttributeName: survey_unique_id
          AttributeType: S
      KeySchema:
# TODO: consider different keyType options?
        - AttributeName: survey_unique_id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  surveyResponses:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: surveyResponses
      AttributeDefinitions:
        - AttributeName: survey_unique_id
          AttributeType: S
        - AttributeName: question_text
          AttributeType: S
      KeySchema:
# TODO: consider different keyType options?
        - AttributeName: survey_unique_id
          KeyType: HASH 
        - AttributeName: question_text
          KeyType: HASH 
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  codeToSurvey:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: codeToSurvey
      AttributeDefinitions:
        - AttributeName: survey_code
          AttributeType: S
      KeySchema:
# TODO: consider different keyType options?
        - AttributeName: survey_code
          KeyType: HASH 
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1