service: surveyless

provider: 
  name: aws
  runtime: python3.6
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  # CreateSurveyFunction:
  #   handler: CreateSurveyFunction/lambda_function.lambda_handler
  #   runtime: python3.6
  #   description: ''
  #   memorySize: 512
  #   timeout: 15
   ## CodeUri: .debug/
    # events:
    #   - http: 
    #       path: /createSurvey
    #       method: POST
    #       cors: true
  
  twilioResponse:
    handler: TwilioResponse/handler.handler
    events:
      - http:
          path: sms
          method: post
          cors: true
  createsurvey:
    handler: SurveyAdmin/create.create
    events:
      - http:
          path: survey
          method: post
          cors: true
  listsurvey:
    handler: SurveyAdmin/list.list
    events:
      - http:
          path: survey
          method: get
          cors: true

  getsurvey:
    handler: SurveyAdmin/get.get
    events:
      - http:
          path: survey/{id}
          method: get
          cors: true

  updatesurvey:
    handler: SurveyAdmin/update.update
    events:
      - http:
          path: survey/{id}
          method: put
          cors: true

  deletesurvey:
    handler: SurveyAdmin/delete.delete
    events:
      - http:
          path: survey/{id}
          method: delete
          cors: true

  createSurveyResponse:
    handler: SurveyResponse/create.create
    events:
      - http:
          path: surveyResponses
          method: post
          cors: true
  listSurveyResponse:
    handler: SurveyResponse/list.list
    events:
      - http:
          path: surveyResponses
          method: get
          cors: true

  getSurveyResponse:
    handler: SurveyResponse/get.get
    events:
      - http:
          path: surveyResponses/{id}
          method: get
          cors: true

  deleteSurveyResponse:
    handler: SurveyResponse/delete.delete
    events:
      - http:
          path: surveyResponses/{id}
          method: delete
          cors: true
resources:
  Resources:
    surveyQuestions:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: surveyQuestionsInfo
        AttributeDefinitions:
          - AttributeName: survey_unique_id
            AttributeType: S
        KeySchema:
  # TODO: consider different keyType options?
          - AttributeName: survey_unique_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    surveyResponses:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: surveyResponses
        AttributeDefinitions:
          - AttributeName: survey_unique_id
            AttributeType: S
        KeySchema:
  # TODO: consider different keyType options?
          - AttributeName: survey_unique_id
            KeyType: HASH 
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
